spring.application.name: dynamodbjava
amazon:
  dynamodb:
    endpoint: http://localhost:8000/


  aws:
    region:
    accesskey: AKIAXXXXXXXXXXXXXXXX
    secretkey: XXXXXXXXXXXXXXX++XXXXXXXXXXXXXXXXXXXXXXX